== Environment
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

This workshop requires a prepared environment for running OpenShift
(specifically, https://www.okd.io/[okd], "the Origin Community Distribution of Kubernetes that powers Red Hat OpenShift").
A https://www.vagrantup.com/[Vagrant box] is provided for setting up this environment on your local machine.
Please perform the following steps before coming to the workshop.

=== Requirements

* https://www.virtualbox.org/[VirtualBox 5.2] installed
* https://www.vagrantup.com/[Vagrant 2.x] installed
* Resources to run the VM with 6 GB of RAM and two virtual CPUs
* https://www.vagrantup.com/[Java 1.8] and http://maven.apache.org/[Maven 3] installed if you'd like to adjust the source code of any of the examples
* A http://github.com/[GitHub] account

=== Set-Up

Begin by creating a fork of the https://github.com/debezium/microservices-lab[microservices-lab] GitHub repository under your own GitHub user.
Then clone your forked repository to your _local machine_, add the upstream repo as another remote repository and pull the latest changes from `upstream/master`:

[source, sh]
git clone git@github.com:<your user>/microservices-lab.git
cd microservices-lab
git remote add upstream git@github.com:debezium/microservices-lab.git
git pull upstream master

=== Build the Projects

In order to obtain all the needed Maven dependencies before coming to the workshop, run the following builds once:

[source, sh]
mvn clean install -f eventr/pom.xml
mvn clean install -f ticket-msa/invoice/pom.xml
mvn clean install -f ticket-msa/order/pom.xml

=== Provision Vagrant Box

Change to the _vm-setup_ directory:

[source, sh]
cd vm-setup

Note: The VM definition (in _Vagrantfile_) uses a fixed IP of 192.168.33.10.
Please change it to a different value in the same network, should this address already be used by a different machine.

Provision the VM using Vagrant:

[source, sh]
vagrant up

This will download the box and start it up.
Once that's done, you should be able to SSH into the box:

[source, sh]
vagrant ssh

Verify you can run `sudo su - build`. After that, exit the box and shut it down:

[source, sh]
vagrant halt

=== Alternative: Set-Up on Custom Cloud Box

The environment can also be set up on a cloud box you can SSH into.
You'll need to have Ansible 2.4 installed in this case on your local machine.

Note: The Vagrant set-up is strongly recommended, as it's unclear still whether it will be possible to SSH into remote hosts from within the conference network.

Clone the workshop repo:

[source, sh]
git clone https://github.com/debezium/microservices-lab.git
cd microservices-lab/vm-setup

Create a file _hosts_ with the following contents:

[source]
<YOUR CLOUDBOX IP> ansible_ssh_private_key_file=~/.ssh/your_ssh_key ansible_python_interpreter=/usr/bin/python3

Provision the environment using Ansible:

[source, sh]
ansible-playbook -i hosts site.yml

Now, let's start the lab with <<module-01#,module 1>>.
