== Environment

This lab requires a prepared environment for running OpenShift.

There are two two ways of preparing this environment:

* On your local machine using Vagrant
* On a cloud machine that you can access using SSH

In both cases the VM running OpenShift should have 6 GB of RAM or more.
An Ansible playbook is provided for setting up the environment.
Please perform these steps before coming to the workshop.

=== Requirements

* Ansible 2.4 or newer installed
* Vagrant installed or access to a VM in the cloud that you can SSH into

=== Set-Up

==== Using Vagrant

Clone the workshop repo:

[source, sh]
git clone https://github.com/debezium/microservices-lab.git
cd microservices-lab/vm-setup

Provision the VM using Vagrant:

[source, sh]
vagrant up

==== Using a Cloud Machine

Clone the workshop repo:

[source, sh]
git clone https://github.com/debezium/microservices-lab.git
cd microservices-lab/vm-setup

Create a file _hosts_ with the following contents:

[source]
<YOUR IP> ansible_ssh_private_key_file=~/.ssh/your_ssh_key ansible_python_interpreter=/usr/bin/python3

Provision the environment using Ansible:

[source, sh]
ansible-playbook -i hosts site.yml

Now, let's start the lab.
